FROM golang:latest

WORKDIR /app

ENV USERS_SERVICE_URL="http://"
ENV TRANSACTION_SERVICE_URL="http://"
ENV APPS_PORT=8081

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o main .

EXPOSE $APPS_PORT

CMD ["./main"]